name: say_hello

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: |
          echo "Hello world"

      - name: Print Date
        run: |
          echo "Now it is: $(date)"

      - name: Print Directory Content
        run: |
          ls -al

      - name: Run hello.yml
        run: |
          echo "hello world"
